services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    expose: ["5173"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
     # - scalar
    ports: ["80:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend/prisma:/app/prisma
      - /app/node_modules
